version: "3.9"

services:
  schematicsdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: schematicsmssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Schematics123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - schematicsnetwork

  schematicsapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schematicsapi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - schematicsdb
    networks:
     - schematicsnetwork

networks:
 schematicsnetwork:
  driver: bridge

volumes:
  mssql_data:
  